Algoritmo "Atvidade7"
// Trilha   : [Algoritimo]
// Professor   : José Erinaldo da Fonseca 
// Autor(a)    : Mariana da Silva Gigliotti
// Data atual  : 13/01/2023
Var
base_maior: real
base_menor: real
altura: real
area: real

Inicio

Escreval ("Digite o valor da base MAIOR:")
leia (base_maior)
Escreval ("base MENOR:")
leia (base_menor)
Escreval ("altura:")
leia (altura)

area <- (base_maior + base_menor) * altura/2

Escreval ()
Escreval ("A área do trapézio é", area, ".")

Fimalgoritmo
