Algoritmo "Atvidade1"
// Trilha   : [Algoritimo]
// Professor   : José Erinaldo da Fonseca
// Autor(a)    : Mariana da Silva Gigliotti
// Data atual  : 13/01/2023
Var
nome: caractere
conta: inteiro
agencia: inteiro

Inicio
Escreval ("Digite o seu nome:")
leia (nome)
Escreval ("Conta:")
leia (conta)
Escreval ("Agência:")
leia (agencia)

Escreval ()
Escreval ("Seus dados são:")
Escreval (nome)
Escreval (conta)
Escreval (agencia)

Fimalgoritmo