Algoritmo "Atvidade4"
// Trilha   : [Algoritimo]
// Professor   : José Erinaldo da Fonseca 
// Autor(a)    : Mariana da Silva Gigliotti
// Data atual  : 13/01/2023
Var
ano_atual: inteiro
ano_nascimento: inteiro
idade: inteiro

Inicio

Escreval ("Digite o ano atual:")
leia (ano_atual)
Escreval ("Digite o ano de nascimento:")
leia (ano_nascimento)

idade <- ano_atual - ano_nascimento

Escreval ()
Escreval ("Idade =", idade, " anos.")

Fimalgoritmo
