Algoritmo "Atvidade6"
// Trilha   : [Algoritimo]
// Professor   : José Erinaldo da Fonseca 
// Autor(a)    : Mariana da Silva Gigliotti
// Data atual  : 13/01/2023
Var
temp_celsius: real
temp_fahrenheit: real

Inicio

Escreval ("Digite a temperatura em fahrenheit:")
leia (temp_fahrenheit)

temp_celsius <- (temp_fahrenheit - 32) * (5/9)

Escreval ()
Escreval ("Temperatura =", temp_celsius, " ºC")

Fimalgoritmo
